name: Continuous integration
on:
  push:
    branches:
      - develop
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      arangodb:
        image: arangodb:3.10.9
        env:
          ARANGO_ROOT_PASSWORD: rootpass
        ports:
          - 8529/tcp
    steps:
      - name: check out code
        uses: actions/checkout@v3
      - name: set up golang
        uses: actions/setup-go@v4
        with:
          go-version: '~1.20.6'
      - run: go version
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          ARANGO_USER: root
          ARANGO_PASS: rootpass
          ARANGO_HOST: localhost
          ARANGO_PORT: ${{ job.services.arangodb.ports[8529] }}
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./profile.cov
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: set up golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: check out code
        uses: actions/checkout@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v2
      - name: cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: log into dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: get short sha
        id: sha
        run: |
          echo "id=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_OUTPUT
      - name: get current branch name
        id: branch
        run: |
          echo "id=$(echo $GITHUB_REF_NAME | sed -e 's/\//-/')" >> $GITHUB_OUTPUT
      - name: docker build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          file: build/package/Dockerfile
          tags: dictybase/modware-stock:${{ steps.branch.outputs.id }}-${{ steps.sha.outputs.id }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
