name: Test coverage
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: set up golang
        uses: actions/setup-go@v2-beta
        with:
          go-version: 1.13.12
      - name: check out code
        uses: actions/checkout@v2
      - name: unit test
        run: go test -covermode=atomic -coverprofile=profile.cov -v ./...
        env:
          GOPROXY: https://proxy.golang.org
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          file: ./profile.cov
          token: ${{ secrets.CODECOV_TOKEN }}
